### ISSUE TITLE
Use auto-generated client library

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/alloydb-go-connector#257]
### Feature Description

Let's use the autogenerated client library and remove the hand-written code.

See https://github.com/googleapis/google-cloud-go/tree/alloydb/v0.1.0/alloydb.

Note: we're depending on v1beta APIs so let's use that for now. When the APIs launch to v1, we should upgrade then.

**Comment by jackwotherspoon** [comment]
This was completed as part of #268
