### ISSUE TITLE
Configurable AlloyDB API endpoint

### ISSUE THREAD

**Issue by mjacobs** [GoogleCloudPlatform/alloydb-go-connector#63]
For testing purposes, it would be helpful for the AlloyDB API endpoint to be configurable.

E.g.  exposing a mechanism to specify this value:

https://github.com/GoogleCloudPlatform/alloydb-go-connector/blob/5b8c8c1d9e824035b080864e5abc869d52cc6daa/internal/alloydbapi/client.go#L48

**Comment by enocom** [comment]
Fixed in https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/pull/67.
